img = imread('./img/VOC_2007_cropped/aeroplane/train/000000.jpg');
model = load('/home/liangfu/Documents/exampler_svm/cnn_students/results_VOC/models/aeroplane/hog_esvm_aeroplane_000000_wo_hn.mat');
model = model.m;
wex = model.w;
b = model.b;
img = imresize(double(img),[100 150]);
%img_1 = img;
img_1 = img(:,end:-1:1,:) ;
params = esvm_get_default_params;
img_2 = imread('/home/liangfu/Desktop/airplane_in_front_3.jpg');
img_2 = imresize(double(img_2),[100 150]);
[feature, ~] = esvm_extract_hog_feature(img, params.features_params.hog_params);
[feature_1, ~] = esvm_extract_hog_feature(img_2, params.features_params.hog_params);
score = wex*feature' - b;
score_1 = wex*feature_1' - b;
figure(1);
imshow(mat2gray(img_2));
figure(2);
imshow(mat2gray(img));
